name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when wiki directory changes
      #- 'documentation/**'
    branches:
      # And only on master branch
      #- master

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the project
      uses: actions/checkout@v2
      with:
        path: project

    - name: Checkout the Wiki repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki

    - name: Update wiki from documentation folder
      run: |
        cd wiki
        git config --local http.sslVerify false
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git config --list --local
        git add -A
        git commit -m "Auto-update from documentation folder"
        git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git
      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

#rsync -avh --exclude .git project/documentation/ wiki/ --delete
        